from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from staffagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Opportunity Advocate conversation history"
    ]
    bear_history: Annotated[
        str, "Challenge Sentinel conversation history"
    ]
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Research chair's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Bold analyst conversation history"
    ]
    safe_history: Annotated[
        str, "Guarded analyst conversation history"
    ]
    neutral_history: Annotated[
        str, "Balanced analyst conversation history"
    ]
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the bold analyst"
    ]
    current_safe_response: Annotated[
        str, "Latest response by the guarded analyst"
    ]
    current_neutral_response: Annotated[
        str, "Latest response by the balanced analyst"
    ]
    judge_decision: Annotated[str, "Risk lead's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Initiative, unit, or organisation under review"]
    trade_date: Annotated[str, "Planning date for the current staff review"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Strategic Analyst briefing"]
    sentiment_report: Annotated[str, "Marketing & Customer Analyst briefing"]
    news_report: Annotated[
        str, "Risk & External Analyst briefing"
    ]
    fundamentals_report: Annotated[str, "Operational Analyst briefing"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the opportunity vs. challenge debate"
    ]
    investment_plan: Annotated[str, "Integrated plan generated by the research council"]

    trader_investment_plan: Annotated[str, "Coordination plan generated by the Staff Lead"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final organisational decision from the Risk Lead"]
